site_name: CompScienceMeshes.jl
repo_url: https://github.com/krcools/CompScienceMeshes.jl
docs_dir: 'build'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

pages:
  - Home: index.md
  - Example: example.md
